# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Division N Spring Conference"
email: "devfest@gdg.org.ua"
description: "Annual Toastmasters Public Speaking Competition. April 14. The Hague. Doors open at 10 AM."
baseurl: ""
url: "http://divisionnconf.nl/"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-114991250-1"
googleAnalyticsSiteUrl: "divisionNconf.nl"
siteVerification: ""

# Organizer Info
organizerName: "Toastmasters"
organizerAlternateName: "Toastmasters"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "lviv@gdg.org.ua"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://lviv.gdg.org.ua/"

# Head
metaKeywords: "event, toastmaster, the hague, conference, competition"
twitterAccount: "#divisionNconf"
socialImageSrcGooglePlus: "/img/seo/division-n-banner.png"
socialImageSrcTwitter: "/img/seo/division-n-banner.png"
socialImageSrcFacebook: "/img/seo/division-n-banner.png"

# Documents
c4pUrl: "https://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/schedule/", text: "Schedule"}
# - {permalink: "/speakers/", text: "Speakers"}
bottomNavigationLinks:
 - {link: "#tickets", text: "Register"}
rightNavigationButtons:
 - {link: "#tickets", text: "Register"}

# Hero Block
heroImage: "toastmasters-hero.jpg"
heroTitle: "Annual Toastmasters <br/>Public Speaking Competition"
eventDate: "April 14"
typeoutTextValues: ''
typeoutFallback: "Season"
heroButtons:
 - {permalink: "/#tickets", text: "Register"}

# About Block
aboutTitle: "What to expect?"
aboutBlock:
 - {title: "Workshops", image: "conference.jpg", text: "Learn new skills in NLP, emotional control and working culture" }
 - {title: "Speech Competition", image: "workshop.jpg", text: "Learn from the best speakers from South-West Netherlands" }
 - {title: "Evaluation Competition", image: "hackathon.jpg", text: "Providing feedback can be hard. Check out how to do that proficiently" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "350", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "48", specialCharacter: "+", info: "hours", detail: "of pure Google technologies"}
 - {count: "20", specialCharacter: "+", info: "speakers", detail: "from country and beyond"}
 - {count: "3", specialCharacter: "", info: "parallel tracks", detail: "plus entertainment lounge"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Workshop speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Leiden University, Wijnhaven Building, Campus The Hague"
eventLocationLink: "http://www.dearchitect.nl/architectuur/nieuws/2018/02/winnaar-nieuwe-berlagevlag-2017-bekend-101187875"
eventStreetAddress: "Turfmarkt 99"
eventAddressLocality: "The Hague"
eventAddressLocalityRegion: "South Holland"
eventPostalCode: "2511 DP"
eventAddressCountry: "Netherlands"
eventStartTime: "2018-04-14T10:00"
eventDoorTime: "10:00"
eventEndTime: "2018-04-14T18:00"
eventPlaceCoordinates: "52.078699, 4.320073"
mapCenterCoordinates: "52.0786937,4.3189241"
mapMobileCenterCoordinates: "52.0786655, 4.3178952"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Campus The Hague"
venueFeatures: ["3 workshop rooms", "Conference hall for 130 people", "Located next to the Central Station"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "Follow us at"
twitterHashTag: "divisionNconf"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Tickets"
ticketsInfo: "Tickets grant access to workshops, competition and coffee brakes. Lunch is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Early Bird"
  price: "FREE"
  priceCurrency: ""
  ticketsNumber: "130"
  ribbon: ""
  buyButtonLink: "https://goo.gl/forms/U6YJyOiFMYF5pzrG2"
  buyButtonText: "Register"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2018-03-01T00:00"
  validThrough: "2018-04-13T23:59"
 -
  name: "At the Door"
  price: "5"
  priceCurrency: "EUR"
  ticketsNumber: ""
  ribbon: ""
  buyButtonLink: ""
  buyButtonText: ""
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2018-04-14T09:00"
  validThrough: "2018-04-14T23:59"
  disabled: true

# Footer
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://www.toastmasters.org/", text: "Toastmasters International"}
   - {link: "https://toastmasters.nl/en/", text: "Toastmasters NL"}
# -
#  title: "Contacts"
#  links:
#   - {link: "mailto:lviv@gdg.org.ua", text: "lviv@gdg.org.ua"}
 -
  title: "FAQ"
  links:
   - {permalink: "https://toastmasters.nl/en/how-toastmasters-works", text: "What is Toastmasters?"}
   - {permalink: "http://dashboards.toastmasters.org/Division.aspx?id=59&hideclub=1", text: "How big is Division N?"}
 -
  title: "Resources"
  links:
   - {permalink: "https://drive.google.com/drive/folders/1XAH1b9-7S5ka5ltd8I0TRnlXHhv31T_s?usp=sharing", text: "Media Kit"}


# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Lviv"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
